version: "3.9"

services:
  devopsdb:
    image: swaroopkumar007/automation:db
    ports:
      - "3306:3306"
    deploy:
      replicas: 2
    networks:
      - app_network

  application:
    image: swaroopkumar007/automation:app
    ports:
      - "1111:8080"
    deploy:
      replicas: 4
    depends_on:
      - devopsdb
    networks:
      - app_network

networks:
  app_network:
    driver: overlay
